Code-Reviews-added-headers-to-be-expanded-on
Paddyjh/Software-Quality-Assurance-Group-10 pull request #3
Opened 2024-03-20 16:30 UTC by Rosscrowley

I have added headers for the Code Review topic.

2024-03-20 16:45 UTC, Paddyjh requested changes
I think we should hold off on merging until we have content we are happy with for each of the topics.

2024-03-20 16:46 UTC, Isaac811 commented
Fair play. I agree


Best regards

Jiayu Liu


Patrick Haughey ***@***.***>于2024年3月20日 周三16:45写道：

> ***@***.**** requested changes on this pull request.
>
> I think we should hold off on merging until we have content we are happy
> with for each of the topics.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Paddyjh/Software-Quality-Assurance-Group-10/pull/3#pullrequestreview-1949483826>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARJDY6Y5KC355ZAWIARZPHLYZG4KRAVCNFSM6AAAAABE72IIXSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNBZGQ4DGOBSGY>
> .
> You are receiving this because you were assigned.Message ID:
> <Paddyjh/Software-Quality-Assurance-Group-10/pull/3/review/1949483826@
> github.com>
>

2024-03-21 22:56 UTC, Isaac811 approved these changes

2024-03-24 14:04 UTC, Paddyjh requested changes
Left a few suggestions and corrections. Any questions just lemme know !

2024-03-24 14:04 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +# **Quality Assurance Handbook**
I think we should remove the bold syntax; since headers are already bold, the "**" isn't needed. Removing this should make it easier when merging into main

2024-03-24 14:04 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +    - Pair Programming - where a developer codes and gets real-time feedback (code review) on their code.
I think we could clarify that this involves two coders programming together, which is where the real-time feedback comes from. Although maybe this is implied enough by the title?

2024-03-24 14:04 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +    - Small, incremental code changes should be the aim as code with many lines is more straneous to review.
Spelling mistake: "straneous" should be "strenuous"

2024-03-24 14:04 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +    - The reviewer should be experienced enough, so that they know what they are looking for such as design, logic, and bugs
To make this sentence flow better, we could rephrase it to something like "... what they are looking for, such as issues relating to design, logic and bugs".

2024-03-24 14:04 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +        - Seems simple but ensure you reply to comments left by a reviewer as well as thanking them for taking the time to review your code.
Maybe changing the start of this to "It seems simple ..." could make this flow better. Alternatively we could just Start the sentence at "Ensure you reply ..."

2024-03-24 14:54 UTC, Rosscrowley commented on Handbook/QA Handbook.md
> +# **Quality Assurance Handbook**
I agree @Paddyjh,  will make that change, thanks.

2024-03-24 14:59 UTC, Rosscrowley commented on Handbook/QA Handbook.md
> +    - Pair Programming - where a developer codes and gets real-time feedback (code review) on their code.
I agree, I will alter the sentence slightly to make it clearer. Thanks.

2024-03-24 15:03 UTC, Rosscrowley commented on Handbook/QA Handbook.md
> +    - The reviewer should be experienced enough, so that they know what they are looking for such as design, logic, and bugs
Agreed, will reword the sentence.

2024-03-24 21:08 UTC, Isaac811 requested changes
Let me know if you have a questoins , left 2 comments there. Thanks!

2024-03-24 21:08 UTC, Isaac811 commented on Handbook/QA Handbook.md
> +    - Reviewee must be receptive to feedback. They must have a willingness to learn and understand criticism is not personal.
Maybe we could change this to “code must be reviewed and tested by the reviewee” to ensure code is also fully tested before a code review.

2024-03-24 21:08 UTC, Isaac811 commented on Handbook/QA Handbook.md
> +- Google mandates code reviews and and follows the Pre-commit review. Below is a diagram of their Code Review Flow.
Remove the double “and” in this sentence.

2024-03-24 23:05 UTC, Rosscrowley commented on Handbook/QA Handbook.md
> +    - Reviewee must be receptive to feedback. They must have a willingness to learn and understand criticism is not personal.
I will add that in. thanks Isaac!

2024-03-24 23:06 UTC, Rosscrowley commented on Handbook/QA Handbook.md
> +- Google mandates code reviews and and follows the Pre-commit review. Below is a diagram of their Code Review Flow.
Thanks for spotting this Isaac!

2024-03-24 23:13 UTC, Rosscrowley commented on Handbook/QA Handbook.md
> +    - Reviewee must be receptive to feedback. They must have a willingness to learn and understand criticism is not personal.
updated in latest commit

2024-03-24 23:13 UTC, Rosscrowley commented on Handbook/QA Handbook.md
> +- Google mandates code reviews and and follows the Pre-commit review. Below is a diagram of their Code Review Flow.
updated in latest commit

2024-03-24 23:44 UTC, Isaac811 commented on Handbook/QA Handbook.md
> +    - Reviewee must be receptive to feedback. They must have a willingness to learn and understand criticism is not personal.
The Reviewers might spell wrong?

2024-03-24 23:49 UTC, Rosscrowley commented on Handbook/QA Handbook.md
> +    - Reviewee must be receptive to feedback. They must have a willingness to learn and understand criticism is not personal.
Apologies, I see my mistake, I will correct now! Thanks.

2024-03-24 23:53 UTC, Rosscrowley commented on Handbook/QA Handbook.md
> +    - Reviewee must be receptive to feedback. They must have a willingness to learn and understand criticism is not personal.
Corrected spelling mistake in latest commit!

2024-03-25 12:47 UTC, Isaac811 approved these changes

2024-03-25 13:54 UTC, Paddyjh requested changes
Everything looks good but i think we can introduce a standard height limit of 500px for diagrams to better organize the overall structure and readability of the document. 

This can be done by using a html image tag and specifying the height rather than the way we are currently doing it. I have attached an example below :

//<img src="name_of_image.png" height="500">

What do yous think ?

2024-03-25 13:59 UTC, Rosscrowley commented
> Everything looks good but i think we can introduce a standard height limit of 500px for diagrams to better organize the overall structure and readability of the document.
> 
> This can be done by using a html image tag and specifying the height rather than the way we are currently doing it. I have attached an example below :
> 
> img src="name_of_image.png" height="500"
> 
> What do yous think ?

@Paddyjh I agree, I will reformat the images. Thanks!

2024-03-25 14:23 UTC, Paddyjh requested changes
Just some small changes before we can merge, thanks

2024-03-25 14:23 UTC, Paddyjh commented on Handbook/QA Handbook.md
> + - A code review is the task of someone who is not the author reviewing a piece of code before it is merged to the main codebase
I think we could rephrase this a bit more clearly

2024-03-25 14:23 UTC, Paddyjh commented on Handbook/QA Handbook.md
> + - A code review is an essential practice to ensure that the code is high quality, aligns with predetermined standards, contains no mistakes
small thing, but maybe we could change this to " and contains no mistakes."

2024-03-25 14:23 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +- Although there are many different approaches to conducting a code review, there are some key practices that should be considered for the code review to be effective.
Could merge these two sentences into one ?

2024-03-25 14:25 UTC, Rosscrowley commented on Handbook/QA Handbook.md
> + - A code review is the task of someone who is not the author reviewing a piece of code before it is merged to the main codebase
Sounds good, how about, "A code review is the process of getting feedback and approval from other developers on submitted code before it is merged into the main codebase."

2024-03-25 14:27 UTC, Paddyjh commented on Handbook/QA Handbook.md
> + - A code review is the task of someone who is not the author reviewing a piece of code before it is merged to the main codebase
That's perfect, thanks!

2024-03-25 15:08 UTC, Paddyjh approved these changes
Looks great, thanks for all the work on this guys!

2024-03-25 15:11 UTC, merged