Feature/task estimation in scrum
Paddyjh/Software-Quality-Assurance-Group-10 pull request #8
Opened 2024-03-23 00:02 UTC by Isaac811

2024-03-23 00:15 UTC, Paddyjh requested changes
This Pr is adding content for the continuous integration topic but it is on the task estimation in scrum branch. I this might have been a mistake @Isaac811

2024-03-23 14:09 UTC, Rosscrowley commented
> This Pr is adding content for the continuous integration topic but it is on the task estimation in scrum branch. I this might have been a mistake @Isaac811

Hey Paddy, I reset the branch to the previous stable commit that you had @Isaac811, so that I can work on my section.

2024-03-23 14:58 UTC, Rosscrowley requested changes

2024-03-23 14:58 UTC, Rosscrowley commented on Handbook/QA Handbook.md
> +Use an example to show these three aspects:
Hey @Isaac811 and @Paddyjh, Do you think we could talk about more specific topics related to task estimation in scrum. The current topics may be to broad and focus more on the scrum process rather than task estimations in scrum.
What do we think about the following topics instead:  
- Estimation Techniques
- Challenges and considerations when accurately estimating task
- Adjusting Estimates During the Sprint
- Team Velocity and calculating Estimation

2024-03-23 15:03 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +Use an example to show these three aspects:
Hey, I think this makes a lot more sense, although I would probably adjust the topic of  "Adjusting Estimates During the Sprint" to something like "Regular Estimation Reviews and Adjustments" so we can talk more about incorporating feedback etc to improve the process.

What do we think ?

2024-03-23 15:09 UTC, Isaac811 commented
Seems all make sense.

Best regards

Jiayu Liu


Patrick Haughey ***@***.***>于2024年3月23日 周六00:16写道：

> ***@***.**** requested changes on this pull request.
>
> This Pr is adding content for the continuous integration topic but it is
> on the task estimation in scrum branch. I this might have been a mistake
> @Isaac811 <https://github.com/Isaac811>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Paddyjh/Software-Quality-Assurance-Group-10/pull/8#pullrequestreview-1956166352>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARJDY65I74OX234DHIVZ6P3YZTCUHAVCNFSM6AAAAABFEEYA6OVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNJWGE3DMMZVGI>
> .
> You are receiving this because you were mentioned.Message ID:
> <Paddyjh/Software-Quality-Assurance-Group-10/pull/8/review/1956166352@
> github.com>
>

2024-03-24 00:03 UTC, Paddyjh requested changes

2024-03-24 00:03 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +![sprint-retrospective-diagram](/Image_Folder/sprint-retrospective-diagram.png)
I think this is a good diagram that explains a lot of information, but I am unsure if it belongs in this section; we could maybe move it somewhere else, or do you guys think it is ok where it is? @Isaac811  @Rosscrowley

2024-03-24 00:03 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +		- Optimism and Individual Bias: Estimators may experience optimism or personal bias which can hinder on an accurate estimation.
I think this could be rephrased to "which can hinder accurate estimation" or something else potentially

2024-03-24 00:03 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +		- Stakeholder / External pressure: Project constraints such as deadlines and budgets can influence the estimation process.
May be worth highlighting how they influence the process, like adding pressure or potentially discussing how this could lead teams to underestimate the length of tasks to try and achieve deadlines. I think this is discussed in the section on avoidances in "Team Velocity and Calculating Estimation below, so maybe we could just link to it?

2024-03-24 00:03 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +		- Parkinson's Law / Changing requirements: Parkinson's law is the observation of work expanding (new requirements) to fill the time available for its completion
I feel like this could be expanded or clarified more to highlight its relevance . Maybe an example or just a few more words could help.

2024-03-24 00:03 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +- The team should experiment with different planning techniques as mentioned previously until they find one that produces the most accuracy for their team
Maybe a diagram of the process of how estimations change and evolve could be useful to add here to help visualise the cyclical nature of this process.

2024-03-24 00:03 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +- Teams should constantly review their team velocity, taking into account both historical and any new data added since the previous calculation
I think a diagram could also be useful here to highlight the cyclical process a team goes through when evaluating its capacity

2024-03-24 00:03 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +![principles-of-good-agile-estimation](/Image_Folder/principles-of-good-agile-estimation.png)
This diagram is great, but it takes up a lot of space. I wonder if it is possible to address this either in markdown or by manually making the diagram smaller.

2024-03-24 17:18 UTC, Rosscrowley commented on Handbook/QA Handbook.md
> +		- Optimism and Individual Bias: Estimators may experience optimism or personal bias which can hinder on an accurate estimation.
I agree, I will rephrase. Thanks

2024-03-24 17:22 UTC, Rosscrowley commented on Handbook/QA Handbook.md
> +		- Stakeholder / External pressure: Project constraints such as deadlines and budgets can influence the estimation process.
I will update this. thanks

2024-03-24 17:22 UTC, Rosscrowley commented on Handbook/QA Handbook.md
> +		- Parkinson's Law / Changing requirements: Parkinson's law is the observation of work expanding (new requirements) to fill the time available for its completion
Agreed, thanks

2024-03-24 19:06 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +![sprint-retrospective-diagram](/Image_Folder/sprint-retrospective-diagram.png)
@Rosscrowley @Isaac811 I just added a diagram to address this comment. What do you guys think?

2024-03-25 12:44 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +- The team should experiment with different planning techniques as mentioned previously until they find one that produces the most accuracy for their team
Added diagram to resolve this

2024-03-25 12:44 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +- Teams should constantly review their team velocity, taking into account both historical and any new data added since the previous calculation
added diagram to resolve this

2024-03-25 14:58 UTC, Rosscrowley commented on Handbook/QA Handbook.md
> +![principles-of-good-agile-estimation](/Image_Folder/principles-of-good-agile-estimation.png)
As discussed in the Feature/code reviews PR, I will update the images to include a Max height of 500. Thanks

2024-03-25 15:14 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +![principles-of-good-agile-estimation](/Image_Folder/principles-of-good-agile-estimation.png)
Brilliant, thanks!

2024-03-25 15:32 UTC, Paddyjh requested changes
Two changes suggested before merging

2024-03-25 15:32 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +	 - Planning Poker: Where team members estimate the effort of a task by playing a number card face down, then discussing all the estimates and coming to an agreement
From reading this, I'm still not entirely sure how planning poker works, do you think we could add a bit more to explain the process?

2024-03-25 15:32 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +- The team should following the following priciples in estimation
change the first "following" to "follow"

2024-03-25 18:48 UTC, Rosscrowley commented on Handbook/QA Handbook.md
> +    - Teams usually measure using units like story points, ideal days or hours.
Given the agile nature of our team, I think we should remove mentioning measuring tasks using days or hours as this no longer fits the agile methodology. Instead, we could describe what a story point measures. Thanks

2024-03-25 19:00 UTC, Rosscrowley approved these changes
Looks good to me!

2024-03-25 19:00 UTC, Paddyjh approved these changes
Look good to me, thanks !

2024-03-25 19:01 UTC, merged