Feature/continuous integration deployment
Paddyjh/Software-Quality-Assurance-Group-10 pull request #9
Opened 2024-03-23 22:22 UTC by Paddyjh

2024-03-23 23:34 UTC, Rosscrowley requested changes
I have left some thoughts that may need to be addressed

2024-03-23 23:34 UTC, Rosscrowley commented on Handbook/QA Handbook.md
> +
Hey @Paddyjh, I think we should maybe add a short introduction to the topic here.

2024-03-23 23:34 UTC, Rosscrowley commented on Handbook/QA Handbook.md
> +- Conduct safety awareness training：Software development teams must understand all the security challenges they may face during the development process. It would be helpful for them to learn about co
Do we think these two bullet points could be broken down into more smaller bullet points?

2024-03-24 00:11 UTC, Paddyjh reviewed
Left some suggestions for potential changes, let me know what you guys think and happy to answer any questions.

2024-03-24 00:11 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +- Conduct safety awareness training：Software development teams must understand all the security challenges they may face during the development process. It would be helpful for them to learn about co
I think that makes a lot of sense @Rosscrowley.

Also, @Isaac811, I feel like this could benefit from a more solid focus on security in continuous integration and deployment, specifically focusing on guidelines and best practices.

2024-03-24 00:11 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +* Adjustment: Feedback received by different departments to make changes. Improvement: Under the agile monitoring and feedback system, fast feedback, fast verification, and fast delivery are inevitab
I really like the diagram and information here, but I think this could be enhanced by incorporating a brief discussion on the benefits or impacts of implementing these feedback loops. Even just a few words at the end of each sentence could suffice.

2024-03-24 10:35 UTC, Rosscrowley commented on Handbook/QA Handbook.md
> +#### Commiting practices
Spelling mistake here, "Commiting" should be "Committing". Thanks!

2024-03-24 10:38 UTC, Rosscrowley commented on Handbook/QA Handbook.md
> +- Infrastructure as code should be used to ensure a consistent environment, tools like terraform and ansible should be utilised
Terraform and Ansible should start with a capital letter. Thanks!

2024-03-24 14:08 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +
Good idea, thanks for spotting. I'll add one now

2024-03-24 19:29 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +
Done

2024-03-24 19:30 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +- Infrastructure as code should be used to ensure a consistent environment, tools like terraform and ansible should be utilised
Done

2024-03-24 19:30 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +#### Commiting practices
Done

2024-03-24 21:06 UTC, Isaac811 requested changes
Left 1 comment, let me know if you have questions.

2024-03-24 21:06 UTC, Isaac811 commented on Handbook/QA Handbook.md
> +	- If an issue is identified we can roll back the application to the previous state and address the issues, which will only affect the canary users
I think you could specify why canary is the best choice for our company specifically.

2024-03-24 21:32 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +	- If an issue is identified we can roll back the application to the previous state and address the issues, which will only affect the canary users
Good Idea, I just added there now. Thanks!

2024-03-24 22:52 UTC, Isaac811 commented on Handbook/QA Handbook.md
> +- Conduct safety awareness training：Software development teams must understand all the security challenges they may face during the development process. It would be helpful for them to learn about co
Please check the updated version and let me what do you think thx.

2024-03-24 22:53 UTC, Isaac811 commented on Handbook/QA Handbook.md
> +* Adjustment: Feedback received by different departments to make changes. Improvement: Under the agile monitoring and feedback system, fast feedback, fast verification, and fast delivery are inevitab
Done.

2024-03-24 23:22 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +- A step-by-step approach to app release that splits traffic between a deployed version and a new version, releasing to a subset of users before a full rollout.
@Isaac811 Did you mean to add this section to the discussion on the feature toggle? What you have added seems to be describing canary releases which are already outlined above

2024-03-25 00:28 UTC, Isaac811 commented on Handbook/QA Handbook.md
> +- A step-by-step approach to app release that splits traffic between a deployed version and a new version, releasing to a subset of users before a full rollout.
Done.

2024-03-25 00:33 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +- A step-by-step approach to app release that splits traffic between a deployed version and a new version, releasing to a subset of users before a full rollout.
Thanks for updating!

2024-03-25 11:55 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +- Conduct safety awareness training：Software development teams must understand all the security challenges they may face during the development process. It would be helpful for them to learn about co
Hey @Paddyjh, I think the new bullet point structure is looking good!

I still think this could benefit from talking about security practices specific to Continuous Integration and Deployment as this is a subsection of the overarching topic of Continuous Integration and Deployment.

Here are one or two articles you may find helpful as a starting point:

- https://vulcan.io/blog/ci-cd-security-5-best-practices/
- https://cycode.com/blog/ci-cd-pipeline-security-best-practices/

If you have any questions, or if you think it is fine the way it is, just let me know!

2024-03-25 12:58 UTC, Isaac811 commented on Handbook/QA Handbook.md
> +- Conduct safety awareness training：Software development teams must understand all the security challenges they may face during the development process. It would be helpful for them to learn about co
I Will update the part. Thanks.

2024-03-25 12:59 UTC, Paddyjh commented on Handbook/QA Handbook.md
> +- Conduct safety awareness training：Software development teams must understand all the security challenges they may face during the development process. It would be helpful for them to learn about co
thanks @Isaac811 !
Give me a shout if you need a hand

2024-03-25 15:05 UTC, Paddyjh commented on Handbook/QA Handbook.md
Hey @Isaac811 and @Rosscrowley, I updated all images in this pr to abide by the new 500px height limit

2024-03-25 18:33 UTC, Isaac811 commented on Handbook/QA Handbook.md
> +- Conduct safety awareness training：Software development teams must understand all the security challenges they may face during the development process. It would be helpful for them to learn about co
Done，Thanks for the help.

2024-03-25 18:34 UTC, Isaac811 commented on Handbook/QA Handbook.md
Looks good Thx!

2024-03-25 19:03 UTC, Isaac811 approved these changes
Looks Good!

2024-03-25 19:06 UTC, Rosscrowley approved these changes
Looks good to me. Nice work guys!

2024-03-25 19:07 UTC, merged